# Generated by Django 4.1.4 on 2023-01-04 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
                ('message_reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rmessages', to=settings.AUTH_USER_MODEL)),
                ('message_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smessages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
